# %APPDATA%/alacritty/alacritty.toml

[env]
TERM = "xterm-256color"

# [shell]
# program = "C:\\Windows\\System32\\wsl.exe"
# args = ["cd ~"]

[window]
startup_mode = "Maximized"
padding.x = 10
padding.y = 10
decorations = "None"
opacity = 0.95
blur = true

[font]
normal.family = "MesloLGS Nerd Font Mono"
size = 12

[selection]
save_to_clipboard = true

[cursor]
style = { shape = "Underline" }

[mouse]
hide_when_typing = false
