# import = [
#     "~/.config/alacritty/themes/alacritty_kanagawa_dragon.toml"
# ]

[env]
TERM = "xterm-256color"

[window]
startup_mode = "Maximized"
padding.x = 10
padding.y = 10

decorations = "Buttonless"

opacity = 0.9
blur = true

#option_as_alt = "Both"

[font]
normal.family = "MesloLGS Nerd Font Mono"

size = 18

[selection]
save_to_clipboard = true

[cursor]
style = { shape = "Underline"}

[mouse]
hide_when_typing = true
