#!/bin/bash

if [[ -z "$JV" ]]; then
	version="11"
else
	version="$JV"
fi

if [[ $version == "8" ]]; then
	export JAVA_HOME=/Library/Java/JavaVirtualMachines/temurin-$version.jdk/Contents/Home
else
	export JAVA_HOME=/opt/homebrew/opt/openjdk@$version/
fi

mvn -V "$@"
